server {
    listen 80;
    listen [::]:80;

    server_name heritage-wear.shop www.heritage-wear.shop;
    root /var/www/heritage/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(?:jpg|jpeg|png|gif|webp|svg|ico|woff2?)$ {
        try_files $uri =404;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }
}
